### ISSUE TITLE
Link to Website does not work

### ISSUE THREAD

**Issue by kweide** [Flash-X/flash-x.io#2]
The link from the Flash-X/Website repo code to the Website does not work for me now.  It used to.

**Comment by akashdhruv** [comment]
https://github.com/Flash-X/Website/settings/pages

**Comment by akashdhruv** [comment]
Issue with DNS settings of the new domain name. This needs to be resolved from the account that owns the domain name.

**Comment by akashdhruv** [comment]
@kweide Added you as the Admin for this repository so you can see settings/pages tab.

**Comment by kweide** [comment]
DNS does not resolve flash-x.org to an address.
When I try `nslookup` at home, DNS does not resolve www.flash-x.org to an address.
When I try `nslookup` **on homes-02.cels.anl.gov**, DNS **does** resolve **www.**flash-x.org to CNAME nginx-proxy.cels.anl.gov.

**Comment by kweide** [comment]
works now.

**Comment by akashdhruv** [comment]
Keeping this open because the domain name flash-x.org still does not work
